version: '2'

services:
  traefik:
    image: containous/traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - testnet

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=test"
      - "traefik.frontend.rule=Host"
      - "traefik.frontend.value=docker.localhost"
    networks:
      - testnet
networks:
  testnet:
    driver: bridge
